// JavaScript | this keyword | 3.31.31
console.clear();

// Understanding the Document Object Model (DOM)
// Targeting DOM Elements

let element = getComputedStyle(title)

/* element.style.backgroundColor = 'burlywood';
element.style.color = 'brown';
element.style.padding='20px'; */
/* 
element.style.cssText = 'background: burlywood; color:brown;padding:20px';
element.style.cssText += 'margin-bottom: 100px'
 */



console.log(element);

/* 

{
    "0": "accent-color",
    "1": "align-content",
    "2": "align-items",
    "3": "align-self",
    "4": "alignment-baseline",
    "5": "animation-delay",
    "6": "animation-direction",
    "7": "animation-duration",
    "8": "animation-fill-mode",
    "9": "animation-iteration-count",
    "10": "animation-name",
    "11": "animation-play-state",
    "12": "animation-timing-function",
    "13": "app-region",
    "14": "appearance",
    "15": "backdrop-filter",
    "16": "backface-visibility",
    "17": "background-attachment",
    "18": "background-blend-mode",
    "19": "background-clip",
    "20": "background-color",
    "21": "background-image",
    "22": "background-origin",
    "23": "background-position",
    "24": "background-repeat",
    "25": "background-size",
    "26": "baseline-shift",
    "27": "block-size",
    "28": "border-block-end-color",
    "29": "border-block-end-style",
    "30": "border-block-end-width",
    "31": "border-block-start-color",
    "32": "border-block-start-style",
    "33": "border-block-start-width",
    "34": "border-bottom-color",
    "35": "border-bottom-left-radius",
    "36": "border-bottom-right-radius",
    "37": "border-bottom-style",
    "38": "border-bottom-width",
    "39": "border-collapse",
    "40": "border-end-end-radius",
    "41": "border-end-start-radius",
    "42": "border-image-outset",
    "43": "border-image-repeat",
    "44": "border-image-slice",
    "45": "border-image-source",
    "46": "border-image-width",
    "47": "border-inline-end-color",
    "48": "border-inline-end-style",
    "49": "border-inline-end-width",
    "50": "border-inline-start-color",
    "51": "border-inline-start-style",
    "52": "border-inline-start-width",
    "53": "border-left-color",
    "54": "border-left-style",
    "55": "border-left-width",
    "56": "border-right-color",
    "57": "border-right-style",
    "58": "border-right-width",
    "59": "border-start-end-radius",
    "60": "border-start-start-radius",
    "61": "border-top-color",
    "62": "border-top-left-radius",
    "63": "border-top-right-radius",
    "64": "border-top-style",
    "65": "border-top-width",
    "66": "bottom",
    "67": "box-shadow",
    "68": "box-sizing",
    "69": "break-after",
    "70": "break-before",
    "71": "break-inside",
    "72": "buffered-rendering",
    "73": "caption-side",
    "74": "caret-color",
    "75": "clear",
    "76": "clip",
    "77": "clip-path",
    "78": "clip-rule",
    "79": "color",
    "80": "color-interpolation",
    "81": "color-interpolation-filters",
    "82": "color-rendering",
    "83": "column-count",
    "84": "column-gap",
    "85": "column-rule-color",
    "86": "column-rule-style",
    "87": "column-rule-width",
    "88": "column-span",
    "89": "column-width",
    "90": "contain-intrinsic-block-size",
    "91": "contain-intrinsic-height",
    "92": "contain-intrinsic-inline-size",
    "93": "contain-intrinsic-size",
    "94": "contain-intrinsic-width",
    "95": "content",
    "96": "cursor",
    "97": "cx",
    "98": "cy",
    "99": "d",
    "100": "direction",
    "101": "display",
    "102": "dominant-baseline",
    "103": "empty-cells",
    "104": "fill",
    "105": "fill-opacity",
    "106": "fill-rule",
    "107": "filter",
    "108": "flex-basis",
    "109": "flex-direction",
    "110": "flex-grow",
    "111": "flex-shrink",
    "112": "flex-wrap",
    "113": "float",
    "114": "flood-color",
    "115": "flood-opacity",
    "116": "font-family",
    "117": "font-kerning",
    "118": "font-optical-sizing",
    "119": "font-size",
    "120": "font-stretch",
    "121": "font-style",
    "122": "font-synthesis-small-caps",
    "123": "font-synthesis-style",
    "124": "font-synthesis-weight",
    "125": "font-variant",
    "126": "font-variant-caps",
    "127": "font-variant-east-asian",
    "128": "font-variant-ligatures",
    "129": "font-variant-numeric",
    "130": "font-weight",
    "131": "grid-auto-columns",
    "132": "grid-auto-flow",
    "133": "grid-auto-rows",
    "134": "grid-column-end",
    "135": "grid-column-start",
    "136": "grid-row-end",
    "137": "grid-row-start",
    "138": "grid-template-areas",
    "139": "grid-template-columns",
    "140": "grid-template-rows",
    "141": "height",
    "142": "hyphens",
    "143": "image-orientation",
    "144": "image-rendering",
    "145": "inline-size",
    "146": "inset-block-end",
    "147": "inset-block-start",
    "148": "inset-inline-end",
    "149": "inset-inline-start",
    "150": "isolation",
    "151": "justify-content",
    "152": "justify-items",
    "153": "justify-self",
    "154": "left",
    "155": "letter-spacing",
    "156": "lighting-color",
    "157": "line-break",
    "158": "line-height",
    "159": "list-style-image",
    "160": "list-style-position",
    "161": "list-style-type",
    "162": "margin-block-end",
    "163": "margin-block-start",
    "164": "margin-bottom",
    "165": "margin-inline-end",
    "166": "margin-inline-start",
    "167": "margin-left",
    "168": "margin-right",
    "169": "margin-top",
    "170": "marker-end",
    "171": "marker-mid",
    "172": "marker-start",
    "173": "mask-type",
    "174": "max-block-size",
    "175": "max-height",
    "176": "max-inline-size",
    "177": "max-width",
    "178": "min-block-size",
    "179": "min-height",
    "180": "min-inline-size",
    "181": "min-width",
    "182": "mix-blend-mode",
    "183": "object-fit",
    "184": "object-position",
    "185": "offset-distance",
    "186": "offset-path",
    "187": "offset-rotate",
    "188": "opacity",
    "189": "order",
    "190": "orphans",
    "191": "outline-color",
    "192": "outline-offset",
    "193": "outline-style",
    "194": "outline-width",
    "195": "overflow-anchor",
    "196": "overflow-clip-margin",
    "197": "overflow-wrap",
    "198": "overflow-x",
    "199": "overflow-y",
    "200": "overscroll-behavior-block",
    "201": "overscroll-behavior-inline",
    "202": "padding-block-end",
    "203": "padding-block-start",
    "204": "padding-bottom",
    "205": "padding-inline-end",
    "206": "padding-inline-start",
    "207": "padding-left",
    "208": "padding-right",
    "209": "padding-top",
    "210": "paint-order",
    "211": "perspective",
    "212": "perspective-origin",
    "213": "pointer-events",
    "214": "position",
    "215": "r",
    "216": "resize",
    "217": "right",
    "218": "row-gap",
    "219": "ruby-position",
    "220": "rx",
    "221": "ry",
    "222": "scroll-behavior",
    "223": "scroll-margin-block-end",
    "224": "scroll-margin-block-start",
    "225": "scroll-margin-inline-end",
    "226": "scroll-margin-inline-start",
    "227": "scroll-padding-block-end",
    "228": "scroll-padding-block-start",
    "229": "scroll-padding-inline-end",
    "230": "scroll-padding-inline-start",
    "231": "scrollbar-gutter",
    "232": "shape-image-threshold",
    "233": "shape-margin",
    "234": "shape-outside",
    "235": "shape-rendering",
    "236": "speak",
    "237": "stop-color",
    "238": "stop-opacity",
    "239": "stroke",
    "240": "stroke-dasharray",
    "241": "stroke-dashoffset",
    "242": "stroke-linecap",
    "243": "stroke-linejoin",
    "244": "stroke-miterlimit",
    "245": "stroke-opacity",
    "246": "stroke-width",
    "247": "tab-size",
    "248": "table-layout",
    "249": "text-align",
    "250": "text-align-last",
    "251": "text-anchor",
    "252": "text-decoration",
    "253": "text-decoration-color",
    "254": "text-decoration-line",
    "255": "text-decoration-skip-ink",
    "256": "text-decoration-style",
    "257": "text-emphasis-color",
    "258": "text-emphasis-position",
    "259": "text-emphasis-style",
    "260": "text-indent",
    "261": "text-overflow",
    "262": "text-rendering",
    "263": "text-shadow",
    "264": "text-size-adjust",
    "265": "text-transform",
    "266": "text-underline-position",
    "267": "top",
    "268": "touch-action",
    "269": "transform",
    "270": "transform-origin",
    "271": "transform-style",
    "272": "transition-delay",
    "273": "transition-duration",
    "274": "transition-property",
    "275": "transition-timing-function",
    "276": "unicode-bidi",
    "277": "user-select",
    "278": "vector-effect",
    "279": "vertical-align",
    "280": "visibility",
    "281": "white-space",
    "282": "widows",
    "283": "width",
    "284": "will-change",
    "285": "word-break",
    "286": "word-spacing",
    "287": "writing-mode",
    "288": "x",
    "289": "y",
    "290": "z-index",
    "291": "zoom",
    "292": "-webkit-border-horizontal-spacing",
    "293": "-webkit-border-image",
    "294": "-webkit-border-vertical-spacing",
    "295": "-webkit-box-align",
    "296": "-webkit-box-decoration-break",
    "297": "-webkit-box-direction",
    "298": "-webkit-box-flex",
    "299": "-webkit-box-ordinal-group",
    "300": "-webkit-box-orient",
    "301": "-webkit-box-pack",
    "302": "-webkit-box-reflect",
    "303": "-webkit-font-smoothing",
    "304": "-webkit-highlight",
    "305": "-webkit-hyphenate-character",
    "306": "-webkit-line-break",
    "307": "-webkit-line-clamp",
    "308": "-webkit-locale",
    "309": "-webkit-mask-box-image",
    "310": "-webkit-mask-box-image-outset",
    "311": "-webkit-mask-box-image-repeat",
    "312": "-webkit-mask-box-image-slice",
    "313": "-webkit-mask-box-image-source",
    "314": "-webkit-mask-box-image-width",
    "315": "-webkit-mask-clip",
    "316": "-webkit-mask-composite",
    "317": "-webkit-mask-image",
    "318": "-webkit-mask-origin",
    "319": "-webkit-mask-position",
    "320": "-webkit-mask-repeat",
    "321": "-webkit-mask-size",
    "322": "-webkit-print-color-adjust",
    "323": "-webkit-rtl-ordering",
    "324": "-webkit-tap-highlight-color",
    "325": "-webkit-text-combine",
    "326": "-webkit-text-decorations-in-effect",
    "327": "-webkit-text-fill-color",
    "328": "-webkit-text-orientation",
    "329": "-webkit-text-security",
    "330": "-webkit-text-stroke-color",
    "331": "-webkit-text-stroke-width",
    "332": "-webkit-user-drag",
    "333": "-webkit-user-modify",
    "334": "-webkit-writing-mode",
    "accentColor": "auto",
    "additiveSymbols": "",
    "alignContent": "normal",
    "alignItems": "normal",
    "alignSelf": "auto",
    "alignmentBaseline": "auto",
    "all": "",
    "animation": "none 0s ease 0s 1 normal none running",
    "animationDelay": "0s",
    "animationDirection": "normal",
    "animationDuration": "0s",
    "animationFillMode": "none",
    "animationIterationCount": "1",
    "animationName": "none",
    "animationPlayState": "running",
    "animationTimingFunction": "ease",
    "appRegion": "none",
    "appearance": "none",
    "ascentOverride": "",
    "aspectRatio": "auto",
    "backdropFilter": "none",
    "backfaceVisibility": "visible",
    "background": "rgba(0, 0, 0, 0) none repeat scroll 0% 0% / auto padding-box border-box",
    "backgroundAttachment": "scroll",
    "backgroundBlendMode": "normal",
    "backgroundClip": "border-box",
    "backgroundColor": "rgba(0, 0, 0, 0)",
    "backgroundImage": "none",
    "backgroundOrigin": "padding-box",
    "backgroundPosition": "0% 0%",
    "backgroundPositionX": "0%",
    "backgroundPositionY": "0%",
    "backgroundRepeat": "repeat",
    "backgroundRepeatX": "",
    "backgroundRepeatY": "",
    "backgroundSize": "auto",
    "baselineShift": "0px",
    "blockSize": "37px",
    "border": "0px none rgb(220, 20, 60)",
    "borderBlock": "0px none rgb(220, 20, 60)",
    "borderBlockColor": "rgb(220, 20, 60)",
    "borderBlockEnd": "0px none rgb(220, 20, 60)",
    "borderBlockEndColor": "rgb(220, 20, 60)",
    "borderBlockEndStyle": "none",
    "borderBlockEndWidth": "0px",
    "borderBlockStart": "0px none rgb(220, 20, 60)",
    "borderBlockStartColor": "rgb(220, 20, 60)",
    "borderBlockStartStyle": "none",
    "borderBlockStartWidth": "0px",
    "borderBlockStyle": "none",
    "borderBlockWidth": "0px",
    "borderBottom": "0px none rgb(220, 20, 60)",
    "borderBottomColor": "rgb(220, 20, 60)",
    "borderBottomLeftRadius": "0px",
    "borderBottomRightRadius": "0px",
    "borderBottomStyle": "none",
    "borderBottomWidth": "0px",
    "borderCollapse": "separate",
    "borderColor": "rgb(220, 20, 60)",
    "borderEndEndRadius": "0px",
    "borderEndStartRadius": "0px",
    "borderImage": "none",
    "borderImageOutset": "0",
    "borderImageRepeat": "stretch",
    "borderImageSlice": "100%",
    "borderImageSource": "none",
    "borderImageWidth": "1",
    "borderInline": "0px none rgb(220, 20, 60)",
    "borderInlineColor": "rgb(220, 20, 60)",
    "borderInlineEnd": "0px none rgb(220, 20, 60)",
    "borderInlineEndColor": "rgb(220, 20, 60)",
    "borderInlineEndStyle": "none",
    "borderInlineEndWidth": "0px",
    "borderInlineStart": "0px none rgb(220, 20, 60)",
    "borderInlineStartColor": "rgb(220, 20, 60)",
    "borderInlineStartStyle": "none",
    "borderInlineStartWidth": "0px",
    "borderInlineStyle": "none",
    "borderInlineWidth": "0px",
    "borderLeft": "0px none rgb(220, 20, 60)",
    "borderLeftColor": "rgb(220, 20, 60)",
    "borderLeftStyle": "none",
    "borderLeftWidth": "0px",
    "borderRadius": "0px",
    "borderRight": "0px none rgb(220, 20, 60)",
    "borderRightColor": "rgb(220, 20, 60)",
    "borderRightStyle": "none",
    "borderRightWidth": "0px",
    "borderSpacing": "0px 0px",
    "borderStartEndRadius": "0px",
    "borderStartStartRadius": "0px",
    "borderStyle": "none",
    "borderTop": "0px none rgb(220, 20, 60)",
    "borderTopColor": "rgb(220, 20, 60)",
    "borderTopLeftRadius": "0px",
    "borderTopRightRadius": "0px",
    "borderTopStyle": "none",
    "borderTopWidth": "0px",
    "borderWidth": "0px",
    "bottom": "auto",
    "boxShadow": "none",
    "boxSizing": "content-box",
    "breakAfter": "auto",
    "breakBefore": "auto",
    "breakInside": "auto",
    "bufferedRendering": "auto",
    "captionSide": "top",
    "caretColor": "rgb(220, 20, 60)",
    "clear": "none",
    "clip": "auto",
    "clipPath": "none",
    "clipRule": "nonzero",
    "color": "rgb(220, 20, 60)",
    "colorInterpolation": "srgb",
    "colorInterpolationFilters": "linearrgb",
    "colorRendering": "auto",
    "colorScheme": "normal",
    "columnCount": "auto",
    "columnFill": "balance",
    "columnGap": "normal",
    "columnRule": "0px none rgb(220, 20, 60)",
    "columnRuleColor": "rgb(220, 20, 60)",
    "columnRuleStyle": "none",
    "columnRuleWidth": "0px",
    "columnSpan": "none",
    "columnWidth": "auto",
    "columns": "auto auto",
    "contain": "none",
    "containIntrinsicBlockSize": "none",
    "containIntrinsicHeight": "none",
    "containIntrinsicInlineSize": "none",
    "containIntrinsicSize": "none",
    "containIntrinsicWidth": "none",
    "content": "normal",
    "contentVisibility": "visible",
    "counterIncrement": "none",
    "counterReset": "none",
    "counterSet": "none",
    "cursor": "auto",
    "cx": "0px",
    "cy": "0px",
    "d": "none",
    "descentOverride": "",
    "direction": "ltr",
    "display": "block",
    "dominantBaseline": "auto",
    "emptyCells": "show",
    "fallback": "",
    "fill": "rgb(0, 0, 0)",
    "fillOpacity": "1",
    "fillRule": "nonzero",
    "filter": "none",
    "flex": "0 1 auto",
    "flexBasis": "auto",
    "flexDirection": "row",
    "flexFlow": "row nowrap",
    "flexGrow": "0",
    "flexShrink": "1",
    "flexWrap": "nowrap",
    "float": "none",
    "floodColor": "rgb(0, 0, 0)",
    "floodOpacity": "1",
    "font": "700 32px sans-serif",
    "fontDisplay": "",
    "fontFamily": "sans-serif",
    "fontFeatureSettings": "normal",
    "fontKerning": "auto",
    "fontOpticalSizing": "auto",
    "fontSize": "32px",
    "fontStretch": "100%",
    "fontStyle": "normal",
    "fontSynthesis": "weight style small-caps",
    "fontSynthesisSmallCaps": "auto",
    "fontSynthesisStyle": "auto",
    "fontSynthesisWeight": "auto",
    "fontVariant": "normal",
    "fontVariantCaps": "normal",
    "fontVariantEastAsian": "normal",
    "fontVariantLigatures": "normal",
    "fontVariantNumeric": "normal",
    "fontVariationSettings": "normal",
    "fontWeight": "700",
    "forcedColorAdjust": "auto",
    "gap": "normal",
    "grid": "none / none / none / row / auto / auto",
    "gridArea": "auto / auto / auto / auto",
    "gridAutoColumns": "auto",
    "gridAutoFlow": "row",
    "gridAutoRows": "auto",
    "gridColumn": "auto / auto",
    "gridColumnEnd": "auto",
    "gridColumnGap": "normal",
    "gridColumnStart": "auto",
    "gridGap": "normal normal",
    "gridRow": "auto / auto",
    "gridRowEnd": "auto",
    "gridRowGap": "normal",
    "gridRowStart": "auto",
    "gridTemplate": "none / none / none",
    "gridTemplateAreas": "none",
    "gridTemplateColumns": "none",
    "gridTemplateRows": "none",
    "height": "37px",
    "hyphens": "manual",
    "imageOrientation": "from-image",
    "imageRendering": "auto",
    "inherits": "",
    "initialValue": "",
    "inlineSize": "1904px",
    "inset": "auto",
    "insetBlock": "auto",
    "insetBlockEnd": "auto",
    "insetBlockStart": "auto",
    "insetInline": "auto",
    "insetInlineEnd": "auto",
    "insetInlineStart": "auto",
    "isolation": "auto",
    "justifyContent": "normal",
    "justifyItems": "normal",
    "justifySelf": "auto",
    "left": "auto",
    "letterSpacing": "normal",
    "lightingColor": "rgb(255, 255, 255)",
    "lineBreak": "auto",
    "lineGapOverride": "",
    "lineHeight": "normal",
    "listStyle": "outside none disc",
    "listStyleImage": "none",
    "listStylePosition": "outside",
    "listStyleType": "disc",
    "margin": "21.44px 0px",
    "marginBlock": "21.44px",
    "marginBlockEnd": "21.44px",
    "marginBlockStart": "21.44px",
    "marginBottom": "21.44px",
    "marginInline": "0px",
    "marginInlineEnd": "0px",
    "marginInlineStart": "0px",
    "marginLeft": "0px",
    "marginRight": "0px",
    "marginTop": "21.44px",
    "marker": "none",
    "markerEnd": "none",
    "markerMid": "none",
    "markerStart": "none",
    "mask": "none",
    "maskType": "luminance",
    "maxBlockSize": "none",
    "maxHeight": "none",
    "maxInlineSize": "none",
    "maxWidth": "none",
    "maxZoom": "",
    "minBlockSize": "0px",
    "minHeight": "0px",
    "minInlineSize": "0px",
    "minWidth": "0px",
    "minZoom": "",
    "mixBlendMode": "normal",
    "negative": "",
    "objectFit": "fill",
    "objectPosition": "50% 50%",
    "offset": "none 0px auto 0deg",
    "offsetDistance": "0px",
    "offsetPath": "none",
    "offsetRotate": "auto 0deg",
    "opacity": "1",
    "order": "0",
    "orientation": "",
    "orphans": "2",
    "outline": "rgb(220, 20, 60) none 0px",
    "outlineColor": "rgb(220, 20, 60)",
    "outlineOffset": "0px",
    "outlineStyle": "none",
    "outlineWidth": "0px",
    "overflow": "visible",
    "overflowAnchor": "auto",
    "overflowClipMargin": "0px",
    "overflowWrap": "normal",
    "overflowX": "visible",
    "overflowY": "visible",
    "overscrollBehavior": "auto",
    "overscrollBehaviorBlock": "auto",
    "overscrollBehaviorInline": "auto",
    "overscrollBehaviorX": "auto",
    "overscrollBehaviorY": "auto",
    "pad": "",
    "padding": "0px",
    "paddingBlock": "0px",
    "paddingBlockEnd": "0px",
    "paddingBlockStart": "0px",
    "paddingBottom": "0px",
    "paddingInline": "0px",
    "paddingInlineEnd": "0px",
    "paddingInlineStart": "0px",
    "paddingLeft": "0px",
    "paddingRight": "0px",
    "paddingTop": "0px",
    "page": "auto",
    "pageBreakAfter": "auto",
    "pageBreakBefore": "auto",
    "pageBreakInside": "auto",
    "pageOrientation": "",
    "paintOrder": "normal",
    "perspective": "none",
    "perspectiveOrigin": "952px 18.5px",
    "placeContent": "normal",
    "placeItems": "normal",
    "placeSelf": "auto",
    "pointerEvents": "auto",
    "position": "static",
    "prefix": "",
    "quotes": "auto",
    "r": "0px",
    "range": "",
    "resize": "none",
    "right": "auto",
    "rowGap": "normal",
    "rubyPosition": "over",
    "rx": "auto",
    "ry": "auto",
    "scrollBehavior": "auto",
    "scrollMargin": "0px",
    "scrollMarginBlock": "0px",
    "scrollMarginBlockEnd": "0px",
    "scrollMarginBlockStart": "0px",
    "scrollMarginBottom": "0px",
    "scrollMarginInline": "0px",
    "scrollMarginInlineEnd": "0px",
    "scrollMarginInlineStart": "0px",
    "scrollMarginLeft": "0px",
    "scrollMarginRight": "0px",
    "scrollMarginTop": "0px",
    "scrollPadding": "auto",
    "scrollPaddingBlock": "auto",
    "scrollPaddingBlockEnd": "auto",
    "scrollPaddingBlockStart": "auto",
    "scrollPaddingBottom": "auto",
    "scrollPaddingInline": "auto",
    "scrollPaddingInlineEnd": "auto",
    "scrollPaddingInlineStart": "auto",
    "scrollPaddingLeft": "auto",
    "scrollPaddingRight": "auto",
    "scrollPaddingTop": "auto",
    "scrollSnapAlign": "none",
    "scrollSnapStop": "normal",
    "scrollSnapType": "none",
    "scrollbarGutter": "auto",
    "shapeImageThreshold": "0",
    "shapeMargin": "0px",
    "shapeOutside": "none",
    "shapeRendering": "auto",
    "size": "",
    "sizeAdjust": "",
    "speak": "normal",
    "speakAs": "",
    "src": "",
    "stopColor": "rgb(0, 0, 0)",
    "stopOpacity": "1",
    "stroke": "none",
    "strokeDasharray": "none",
    "strokeDashoffset": "0px",
    "strokeLinecap": "butt",
    "strokeLinejoin": "miter",
    "strokeMiterlimit": "4",
    "strokeOpacity": "1",
    "strokeWidth": "1px",
    "suffix": "",
    "symbols": "",
    "syntax": "",
    "system": "",
    "tabSize": "8",
    "tableLayout": "auto",
    "textAlign": "start",
    "textAlignLast": "auto",
    "textAnchor": "start",
    "textCombineUpright": "none",
    "textDecoration": "none solid rgb(220, 20, 60)",
    "textDecorationColor": "rgb(220, 20, 60)",
    "textDecorationLine": "none",
    "textDecorationSkipInk": "auto",
    "textDecorationStyle": "solid",
    "textDecorationThickness": "auto",
    "textEmphasis": "none rgb(220, 20, 60)",
    "textEmphasisColor": "rgb(220, 20, 60)",
    "textEmphasisPosition": "over",
    "textEmphasisStyle": "none",
    "textIndent": "0px",
    "textOrientation": "mixed",
    "textOverflow": "clip",
    "textRendering": "auto",
    "textShadow": "none",
    "textSizeAdjust": "auto",
    "textTransform": "none",
    "textUnderlineOffset": "auto",
    "textUnderlinePosition": "auto",
    "top": "auto",
    "touchAction": "auto",
    "transform": "none",
    "transformBox": "view-box",
    "transformOrigin": "952px 18.5px",
    "transformStyle": "flat",
    "transition": "all 0s ease 0s",
    "transitionDelay": "0s",
    "transitionDuration": "0s",
    "transitionProperty": "all",
    "transitionTimingFunction": "ease",
    "unicodeBidi": "normal",
    "unicodeRange": "",
    "userSelect": "auto",
    "userZoom": "",
    "vectorEffect": "none",
    "verticalAlign": "baseline",
    "visibility": "visible",
    "webkitAlignContent": "normal",
    "webkitAlignItems": "normal",
    "webkitAlignSelf": "auto",
    "webkitAnimation": "none 0s ease 0s 1 normal none running",
    "webkitAnimationDelay": "0s",
    "webkitAnimationDirection": "normal",
    "webkitAnimationDuration": "0s",
    "webkitAnimationFillMode": "none",
    "webkitAnimationIterationCount": "1",
    "webkitAnimationName": "none",
    "webkitAnimationPlayState": "running",
    "webkitAnimationTimingFunction": "ease",
    "webkitAppRegion": "none",
    "webkitAppearance": "none",
    "webkitBackfaceVisibility": "visible",
    "webkitBackgroundClip": "border-box",
    "webkitBackgroundOrigin": "padding-box",
    "webkitBackgroundSize": "auto",
    "webkitBorderAfter": "0px none rgb(220, 20, 60)",
    "webkitBorderAfterColor": "rgb(220, 20, 60)",
    "webkitBorderAfterStyle": "none",
    "webkitBorderAfterWidth": "0px",
    "webkitBorderBefore": "0px none rgb(220, 20, 60)",
    "webkitBorderBeforeColor": "rgb(220, 20, 60)",
    "webkitBorderBeforeStyle": "none",
    "webkitBorderBeforeWidth": "0px",
    "webkitBorderBottomLeftRadius": "0px",
    "webkitBorderBottomRightRadius": "0px",
    "webkitBorderEnd": "0px none rgb(220, 20, 60)",
    "webkitBorderEndColor": "rgb(220, 20, 60)",
    "webkitBorderEndStyle": "none",
    "webkitBorderEndWidth": "0px",
    "webkitBorderHorizontalSpacing": "0px",
    "webkitBorderImage": "none",
    "webkitBorderRadius": "0px",
    "webkitBorderStart": "0px none rgb(220, 20, 60)",
    "webkitBorderStartColor": "rgb(220, 20, 60)",
    "webkitBorderStartStyle": "none",
    "webkitBorderStartWidth": "0px",
    "webkitBorderTopLeftRadius": "0px",
    "webkitBorderTopRightRadius": "0px",
    "webkitBorderVerticalSpacing": "0px",
    "webkitBoxAlign": "stretch",
    "webkitBoxDecorationBreak": "slice",
    "webkitBoxDirection": "normal",
    "webkitBoxFlex": "0",
    "webkitBoxOrdinalGroup": "1",
    "webkitBoxOrient": "horizontal",
    "webkitBoxPack": "start",
    "webkitBoxReflect": "none",
    "webkitBoxShadow": "none",
    "webkitBoxSizing": "content-box",
    "webkitClipPath": "none",
    "webkitColumnBreakAfter": "auto",
    "webkitColumnBreakBefore": "auto",
    "webkitColumnBreakInside": "auto",
    "webkitColumnCount": "auto",
    "webkitColumnGap": "normal",
    "webkitColumnRule": "0px none rgb(220, 20, 60)",
    "webkitColumnRuleColor": "rgb(220, 20, 60)",
    "webkitColumnRuleStyle": "none",
    "webkitColumnRuleWidth": "0px",
    "webkitColumnSpan": "none",
    "webkitColumnWidth": "auto",
    "webkitColumns": "auto auto",
    "webkitFilter": "none",
    "webkitFlex": "0 1 auto",
    "webkitFlexBasis": "auto",
    "webkitFlexDirection": "row",
    "webkitFlexFlow": "row nowrap",
    "webkitFlexGrow": "0",
    "webkitFlexShrink": "1",
    "webkitFlexWrap": "nowrap",
    "webkitFontFeatureSettings": "normal",
    "webkitFontSmoothing": "auto",
    "webkitHighlight": "none",
    "webkitHyphenateCharacter": "auto",
    "webkitJustifyContent": "normal",
    "webkitLineBreak": "auto",
    "webkitLineClamp": "none",
    "webkitLocale": "\"en\"",
    "webkitLogicalHeight": "37px",
    "webkitLogicalWidth": "1904px",
    "webkitMarginAfter": "21.44px",
    "webkitMarginBefore": "21.44px",
    "webkitMarginEnd": "0px",
    "webkitMarginStart": "0px",
    "webkitMask": "",
    "webkitMaskBoxImage": "none",
    "webkitMaskBoxImageOutset": "0",
    "webkitMaskBoxImageRepeat": "stretch",
    "webkitMaskBoxImageSlice": "0 fill",
    "webkitMaskBoxImageSource": "none",
    "webkitMaskBoxImageWidth": "auto",
    "webkitMaskClip": "border-box",
    "webkitMaskComposite": "source-over",
    "webkitMaskImage": "none",
    "webkitMaskOrigin": "border-box",
    "webkitMaskPosition": "0% 0%",
    "webkitMaskPositionX": "0%",
    "webkitMaskPositionY": "0%",
    "webkitMaskRepeat": "repeat",
    "webkitMaskRepeatX": "",
    "webkitMaskRepeatY": "",
    "webkitMaskSize": "auto",
    "webkitMaxLogicalHeight": "none",
    "webkitMaxLogicalWidth": "none",
    "webkitMinLogicalHeight": "0px",
    "webkitMinLogicalWidth": "0px",
    "webkitOpacity": "1",
    "webkitOrder": "0",
    "webkitPaddingAfter": "0px",
    "webkitPaddingBefore": "0px",
    "webkitPaddingEnd": "0px",
    "webkitPaddingStart": "0px",
    "webkitPerspective": "none",
    "webkitPerspectiveOrigin": "952px 18.5px",
    "webkitPerspectiveOriginX": "",
    "webkitPerspectiveOriginY": "",
    "webkitPrintColorAdjust": "economy",
    "webkitRtlOrdering": "logical",
    "webkitRubyPosition": "before",
    "webkitShapeImageThreshold": "0",
    "webkitShapeMargin": "0px",
    "webkitShapeOutside": "none",
    "webkitTapHighlightColor": "rgba(0, 0, 0, 0.18)",
    "webkitTextCombine": "none",
    "webkitTextDecorationsInEffect": "none",
    "webkitTextEmphasis": "none rgb(220, 20, 60)",
    "webkitTextEmphasisColor": "rgb(220, 20, 60)",
    "webkitTextEmphasisPosition": "over",
    "webkitTextEmphasisStyle": "none",
    "webkitTextFillColor": "rgb(220, 20, 60)",
    "webkitTextOrientation": "vertical-right",
    "webkitTextSecurity": "none",
    "webkitTextSizeAdjust": "auto",
    "webkitTextStroke": "",
    "webkitTextStrokeColor": "rgb(220, 20, 60)",
    "webkitTextStrokeWidth": "0px",
    "webkitTransform": "none",
    "webkitTransformOrigin": "952px 18.5px",
    "webkitTransformOriginX": "",
    "webkitTransformOriginY": "",
    "webkitTransformOriginZ": "",
    "webkitTransformStyle": "flat",
    "webkitTransition": "all 0s ease 0s",
    "webkitTransitionDelay": "0s",
    "webkitTransitionDuration": "0s",
    "webkitTransitionProperty": "all",
    "webkitTransitionTimingFunction": "ease",
    "webkitUserDrag": "auto",
    "webkitUserModify": "read-only",
    "webkitUserSelect": "auto",
    "webkitWritingMode": "horizontal-tb",
    "whiteSpace": "normal",
    "widows": "2",
    "width": "1904px",
    "willChange": "auto",
    "wordBreak": "normal",
    "wordSpacing": "0px",
    "wordWrap": "normal",
    "writingMode": "horizontal-tb",
    "x": "0px",
    "y": "0px",
    "zIndex": "auto",
    "zoom": "1"
}*/